-- ############################
-- Perlica Official Schema
--
-- https://perlicaos.com
--
-- Copyright 2026. SnowLynxSoftware. All Rights Reserved.
-- ############################

-- AUTH

-- Create ENUM type for issuer values (web, api, mobile, etc.)
CREATE TYPE issuer_type AS ENUM ('web', 'api', 'mobile');

-- Create ENUM type for user types (admin, reader)
CREATE TYPE user_type AS ENUM ('admin', 'reader');

CREATE TABLE IF NOT EXISTS "users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "deleted_at" TIMESTAMP,
    "object_id" UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    "email" TEXT UNIQUE NOT NULL,
    "display_name" TEXT NOT NULL,
    "user_type_key" user_type NOT NULL,
    "password_hash" TEXT,
    "api_key" TEXT UNIQUE,
    "last_login" TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_email ON "users" ("email");
CREATE INDEX IF NOT EXISTS idx_users_object_id ON "users" ("object_id");

CREATE TABLE IF NOT EXISTS "user_login_history" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "deleted_at" TIMESTAMP,
    "user_id" INTEGER NOT NULL REFERENCES "users" ("id"),
    "user_agent" TEXT NOT NULL,
    "ip_address" TEXT NOT NULL,
    "issuer" issuer_type NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_user_login_history_user_id ON "user_login_history" ("user_id");

CREATE TABLE IF NOT EXISTS "sessions" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "deleted_at" TIMESTAMP,
    "session_id" UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    "session_expires_at" TIMESTAMP NOT NULL, --// actual expiry time for this session (can be extended on activity)
    "session_max_expiry_at" TIMESTAMP NOT NULL, --// absolute max expiry time for this session (e.g. 7 days from creation) to prevent infinite sessions
    "user_id" INTEGER NOT NULL REFERENCES "users" ("id"),
    "user_agent" TEXT NOT NULL,
    "ip_address" TEXT NOT NULL,
    "issuer" issuer_type NOT NULL
);

-- // USERS
-- Create a default admin user if it doesn't already exist so we can log in and manage the system after initial setup (requires password reset on first login for security)
INSERT INTO public.users (email, display_name, user_type_key)
VALUES ('snowlynxsoftware@gmail.com', 'MorpheusZero', 'admin')
ON CONFLICT (id) DO NOTHING;

-- // SETTINGS

CREATE TABLE IF NOT EXISTS "app_settings" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "deleted_at" TIMESTAMP,
    "allow_send_emails" BOOLEAN DEFAULT false,
    "is_maintenance_mode" BOOLEAN DEFAULT false,
    "maintenance_mode_message" TEXT,
    "maintenance_mode_url" TEXT
);

INSERT INTO public.app_settings (id, allow_registrations, allow_send_emails, is_maintenance_mode, maintenance_mode_message, maintenance_mode_url)
VALUES (1, true, false, false, 'The site is currently undergoing maintenance. Please check back later.', NULL)
ON CONFLICT (id) DO NOTHING;