-- ############################
-- Perlica Official Schema
--
-- https://perlicaos.com
--
-- Copyright 2026. SnowLynxSoftware. All Rights Reserved.
-- ############################

-- AUTH

-- Create ENUM type for issuer values (web, api, mobile, etc.)
CREATE TYPE issuer_type AS ENUM ('web', 'api', 'mobile');

-- Create ENUM type for user types (admin, reader)
CREATE TYPE user_type AS ENUM ('admin', 'reader');

CREATE TABLE IF NOT EXISTS "users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "deleted_at" TIMESTAMP,
    "object_id" UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    "username" TEXT UNIQUE NOT NULL,
    "user_type_key" user_type NOT NULL,
    "password_hash" TEXT,
    "api_key" TEXT UNIQUE,
    "last_login" TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_users_username ON "users" ("username");

CREATE TABLE IF NOT EXISTS "sessions" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "deleted_at" TIMESTAMP,
    "session_id" UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    "session_expires_at" TIMESTAMP NOT NULL, --// actual expiry time for this session (can be extended on activity)
    "session_max_expiry_at" TIMESTAMP NOT NULL, --// absolute max expiry time for this session (e.g. 7 days from creation) to prevent infinite sessions
    "user_id" INTEGER NOT NULL REFERENCES "users" ("id"),
    "user_agent" TEXT NOT NULL,
    "ip_address" TEXT NOT NULL,
    "issuer" issuer_type NOT NULL
);

-- // BOTS

CREATE TABLE IF NOT EXISTS "bots" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "deleted_at" TIMESTAMP,
    "object_id" UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "docker_image" TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bots_object_id ON "bots" ("object_id");

-- Create ENUM type for bot statuses
CREATE TYPE bot_status AS ENUM ('running', 'stopped', 'error', 'starting', 'stopping');

CREATE TABLE IF NOT EXISTS "bot_instances" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "deleted_at" TIMESTAMP,
    "object_id" UUID DEFAULT gen_random_uuid() UNIQUE NOT NULL,
    "bot_id" INTEGER NOT NULL REFERENCES "bots" ("id"),
    "user_id" INTEGER NOT NULL REFERENCES "users" ("id"),
    "bot_status" bot_status NOT NULL,
    "instance_name" TEXT NOT NULL,
    "docker_image_tag" TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bot_instances_object_id ON "bot_instances" ("object_id");
CREATE INDEX IF NOT EXISTS idx_bot_instances_bot_id ON "bot_instances" ("bot_id");
CREATE INDEX IF NOT EXISTS idx_bot_instances_user_id ON "bot_instances" ("user_id");

CREATE TABLE IF NOT EXISTS "bot_instance_logs" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP DEFAULT (NOW()),
    "modified_at" TIMESTAMP,
    "deleted_at" TIMESTAMP,
    "bot_instance_id" INTEGER NOT NULL REFERENCES "bot_instances" ("id"),
    "log_message" TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_bot_instance_logs_bot_instance_id ON "bot_instance_logs" ("bot_instance_id");